fs = require 'fs'

sites = fs.readdirSync 'build/lib/sites/'
configs = []
for siteDir in sites
	continue if siteDir == '.DS_Store'
	if fs.existsSync "build/lib/sites/#{siteDir}/config.js"
		file = fs.readFileSync "build/lib/sites/#{siteDir}/config.js"
		config = /\/\/ Generated by CoffeeScript 1\.7\.1\s*\((\{[\S\s]*?\})\);/.exec(file)[1]
		configs.push "#{siteDir}: #{config}"

fs.writeFileSync 'build/lib/siteConfig.js', "define({#{configs.join ','}});"